#ifndef AADC_USER_ENABLELOGS_H
#define AADC_USER_ENABLELOGS_H

//#define DEBUG_BRAKE_LOG
//#define DEBUG_COMPOSITE_NOTE_LOG
//#define DEBUG_JURY_RESPONSE_LOG
//#define DEBUG_LANE_WORLD_OUT_LOG
//#define DEBUG_LIGHT_CONTROLLER_LOG
//#define DEBUG_MAP_VIEW_LOG
//#define DEBUG_OBSTACLE_DETECTION_LOG
//#define DEBUG_PARKING_LOG
//#define DEBUG_SPATIO_TEMPORAL_IMAGE_LOG
//#define DEBUG_STEERING_FUSION_DEBUG
//#define DEBUG_WORLD_SERVICE_LOG
//#define DEBUG_WORLD_FILTER_IN_LOG
//#define DEBUG_WORLD_FILTER_OUT_LOG
//#define DEBUG_WORLD_OUT_TEMPLATE_FILTER
//#define DEBUG_VIDEO
//#define DEBUG_MARKER_POS_LOG
//#define DEBUG_POST_OBSTACLE_LOG

#endif //AADC_USER_ENABLELOGS_H
